/* @format */

import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import { Box, Button, FormControl, FormLabel, Input } from '@chakra-ui/react';
import { FormEvent, useState } from 'react';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
	function handleSubmit(event: FormEvent<HTMLFormElement>): void {
		throw new Error('Function not implemented.');
	}

	function setEmail(value: any) {
		throw new Error('Function not implemented.');
	}

	function setPassword(value: string): void {
		throw new Error('Function not implemented.');
	}
	function LoginPage() {
		const [email, setEmail] = useState('');
		const [password, setPassword] = useState('');

		const handleSubmit = (event: { preventDefault: () => void }) => {
			event.preventDefault();
			// TODO: Handle form submission
		};
	}

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={styles.main}>
				<div className={styles.center}>
					<Image
						className={styles.logo}
						src='/logo.png'
						alt='Next.js Logo'
						width={540}
						height={180}
						priority
					/>
				</div>
				<Box maxW='md' mx='auto' mt='8'>
					<form onSubmit={handleSubmit}>
						<FormControl>
							<FormLabel>Email address</FormLabel>
							<Input
								type='email'
								onChange={(event) => setEmail(event.target.value)}
							/>
						</FormControl>
						<FormControl mt='4'>
							<FormLabel>Password</FormLabel>
							<Input
								type='password'
								onChange={(event) => setPassword(event.target.value)}
							/>
						</FormControl>
						<Button type='submit' colorScheme='blue' mt='4'>
							Log in
						</Button>
					</form>
				</Box>
			</main>
		</>
	);
}
