/* @format */

import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import {
	Box,
	Button,
	FormControl,
	FormLabel,
	Input,
	Flex,
	Heading,
	Center,
} from '@chakra-ui/react';
import { FormEvent, useState } from 'react';
import { useRouter } from 'next/router';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
	function setEmail(value: any) {
		throw new Error('Function not implemented.');
	}

	function setPassword(value: string): void {
		throw new Error('Function not implemented.');
	}
	function LoginPage() {
		const [email, setEmail] = useState('');
		const [password, setPassword] = useState('');

		const handleSubmit = (event: { preventDefault: () => void }) => {
			event.preventDefault();
			// TODO: Handle form submission
		};
	}
	const router = useRouter();

	const handleSubmit = (event: { preventDefault: () => void }) => {
		event.preventDefault();
		// TODO: Handle form submission
		router.push('/dashboard');
	};
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={styles.main}>
				<div className={styles.center}>
					<Image
						className={styles.logo}
						src='/logo.png'
						alt='Next.js Logo'
						width={540}
						height={180}
						priority
					/>
				</div>
				<Flex height={'vh'} alignItems={'center'} justifyContent={'center'}>
					<Flex direction={'column'} background={'grey.300'} p={12} rounded={6}>
						<Heading mb={2}>
							{' '}
							<Center mb={5}>Log In</Center>
							<Input
								placeholder='adminpanel@horsesmouth.in'
								variant='filled'
								mb={3}
								type='email'
							/>
							<Input
								placeholder='******************'
								variant='filled'
								mb={6}
								type='password'
							/>
							<Center>
								<Button
									marginRight='25'
									width='280px'
									mb={50}
									colorScheme='teal'>
									<Link href='/dashboard'>Log In</Link>
								</Button>
								<Button
									marginLeft='25'
									width='280px'
									mb={50}
									colorScheme='teal'>
									<Link href='/signup'>Sign Up</Link>
								</Button>
							</Center>
						</Heading>
					</Flex>
				</Flex>
			</main>
		</>
	);
}
